baseURL = "http://retail-sample.io/"
languageCode = "en-us"
title = "Retail sample"
paginate = 5

copyright = "Â© Copyright notice"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-123-45"
disqusShortname = "ezhil-demo"

[params]
	subtitle = "Clean and minimal personal [blog theme for Hugo](https://github.com/vividvilla/ezhil)"
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	mode = "auto" # "dark", "auto", "light"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	customJS = ["https://code.jquery.com/jquery-3.4.1.js"]  # Custom JS scripts.

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "fkn"
name = "fkn"
url = "/fkn"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3
